// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};
var exports = module.exports = {};

exports.EventsService = {
  EventsService : {
    Events : {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetServiceCapabilitiesResponse = { 
          //Capabilities : { 
            //attributes : {
              //WSSubscriptionPolicySupport : {xs:boolean},
              //WSPullPointSupport : {xs:boolean},
              //WSPausableSubscriptionManagerInterfaceSupport : {xs:boolean},
              //MaxNotificationProducers : {xs:int},
              //MaxPullPoints : {xs:int},
              //PersistentNotificationStorage : {xs:boolean},
              //EventBrokerProtocols : {xs:string},
              //MaxEventBrokers : {xs:int}
            //}
          //}
        //
        //};
        //return GetServiceCapabilitiesResponse;
      },

      //var CreatePullPointSubscription = { 
        //Filter : { },
        //InitialTerminationTime : { simpleType},
        //SubscriptionPolicy : { }
      //
      //};
      CreatePullPointSubscription : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreatePullPointSubscriptionResponse = { 
          //SubscriptionReference : { 
            //Address : { tns:AttributedURIType},
            //ReferenceParameters : { tns:ReferenceParametersType}
          //}
        //
        //};
        //return CreatePullPointSubscriptionResponse;
      },

      //var GetEventProperties = { };
      GetEventProperties : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetEventPropertiesResponse = { 
          //TopicNamespaceLocation : [{ xs:anyURI}],
          //MessageContentFilterDialect : [{ xs:anyURI}],
          //ProducerPropertiesFilterDialect : [{ xs:anyURI}],
          //MessageContentSchemaLocation : [{ xs:anyURI}]
        //
        //};
        //return GetEventPropertiesResponse;
      },

      //var AddEventBroker = { 
        //EventBroker : [{ 
          //Address : [{ xs:anyURI}],
          //TopicPrefix : [{ xs:string}],
          //UserName : [{ xs:string}],
          //Password : [{ xs:string}],
          //CertificateID : [{ xs:token}],
          //PublishFilter : [{ }],
          //QoS : [{ xs:int}],
          //Status : [{ xs:string}]
        //}]
      //
      //};
      AddEventBroker : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddEventBrokerResponse = { };
        //return AddEventBrokerResponse;
      },

      //var DeleteEventBroker = { 
        //Address : [{ xs:anyURI}]
      //
      //};
      DeleteEventBroker : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteEventBrokerResponse = { };
        //return DeleteEventBrokerResponse;
      },

      //var GetEventBrokers = { 
        //Address : [{ xs:anyURI}]
      //
      //};
      GetEventBrokers : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetEventBrokersResponse = { 
          //EventBroker : [{ 
            //Address : [{ xs:anyURI}],
            //TopicPrefix : [{ xs:string}],
            //UserName : [{ xs:string}],
            //Password : [{ xs:string}],
            //CertificateID : [{ xs:token}],
            //PublishFilter : [{ }],
            //QoS : [{ xs:int}],
            //Status : [{ xs:string}]
          //}]
        //
        //};
        //return GetEventBrokersResponse;
      },

    }
  }
}
